public record Datum(
    string bib,
    string name,
    
    string categoryKey,
    string categoryName,
    string categoryParentKey,
    
    string startBlockKey,
    string startBlockStartDate,
    
    string? athlete1Name,
    int? athlete1BirthYear,
    string? athlete1Nationality,
    string? athlete2Name,
    int? athlete2BirthYear,
    string? athlete2Nationality,
    string? athlete3Name,
    int? athlete3BirthYear,
    string? athlete3Nationality,
    
    string status,
    string start,
    string? time,
    int rank,
    int crank,
    string checkPoint00,
    string checkPoint01,
    string checkPoint02,
    string checkPoint03,
    string checkPoint04,
    string checkPoint05,
    string checkPoint06,
    string checkPoint07,
    string checkPoint08,
    string checkPoint09,
    string checkPoint10,
    string checkPoint11,
    string checkPoint12,

    string time_00_01,
    string time_01_02,
    string time_02_03,
    string time_03_04,
    string time_04_05,
    string time_05_06,
    string time_06_07,
    string time_07_08,
    string time_08_09,
    string time_09_10,
    string time_10_11,
    string time_11_12
);